### ISSUE TITLE
Error when closing nvim

### ISSUE THREAD

**Issue by AkisArou** [tmillr/sos.nvim#24]
Hello, thanks for the plugin!

I get an error when I close nvim.
in function verbose at commands.lua:84 when called by function(opts) require('sos').disable(verbose(opts)) end.
attempt to index local 'opts' (a nil value)

If I comment out the opts table access, it works fine:
```
local function verbose(opts)
  -- if opts.smods.emsg_silent or opts.smods.silent then
  --   return opts.smods.unsilent
  -- end
  --
  return true
end
```

**Comment by tmillr** [comment]
Thank you for the report. I'll look into this
